repositoryUrl: https://github.com/Dynamsoft/web-twain-docs/master

docHomePage: /
dynamsoft_logo: /assets/img-icon/dynamsoft-logo.png
dwt_logo: /assets/img-icon/dwt-logo.png
edit_icon: /assets/img-icon/edit-icon.png

assets: /assets/
_includes: /_includes/
_layouts: /_layouts/
about: /web-twain/docs/about/
getstarted: /getstarted/
indepth: /indepth/
info: /info/
theme: jekyll-theme-cayman